### ISSUE TITLE
Create a dictionary for common terms used through code/documentation

### ISSUE THREAD

**Issue by mosteo** [alire-project/alire-index#44]
It may help to precisely define polysemic words in the Alire context:

package: is Ada sense or what?
project: is GPR sense or what?

What is meant exactly by session/workspace/sandbox?

And so on.

**Comment by Fabien-Chouteau** [comment]
Hi @mosteo,

I thought about this a couple of time, in particular we need an Alire name for the packages.
Maybe modules or something more creative like Cargo and its crates.

**Comment by mosteo** [comment]
I have started to collect the most common terms in https://github.com/alire-project/alire/wiki. You are right, the "alire-packaged things" is the most confusing one right now.

**Comment by pmderodat** [comment]
Thanks for the glossary, Alejandro!

Now, question for the posterity: should we say that Alire is a “package manager” or a “project manager”? ;-) More seriously, the fact that we still have confusing terms (they are formally defined, but still heavily overloaded) reminds me about @Fabien-Chouteau's suggestions to use dedicated vocabulary with real-world comparisons, such as Cargo/Crates in Rust land.

**Comment by mosteo** [comment]
Well, it's a "LIbrary REpository" ;-) so a "library manager", which is more general than packages (that evokes Ada packages) and gprbuild projects (if we think of a hypothetical future in which another OS Ada compiler exists). Even though some projects are not libraries. Oh well :-)

Yes, if we could think of something truly specific for alr-indexed projects, that would be good. From "À lire" we could use "book" but that's really far-fetched... 

Gotta keep thinking...

**Comment by Fabien-Chouteau** [comment]
Talked about this with @raph-amiard, he said we can actually re-use the word crates from Cargo.

**Comment by mosteo** [comment]
True that. I wonder if that could complicate things down the road with e.g. internet searches though.

**Comment by mosteo** [comment]
Throwing a few more into the mix:
- bundle / parcel / lot
- unit / module
- quantum

**Comment by mosteo** [comment]
Crate adopted, wiki updated, closing.
